# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
variables: 
  CURRENT_SHA : $(system.pullRequest.sourceCommitId)
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    git checkout happoConfiguration
    value=$( sed 's/....$//' <<< $(System.PullRequest.SourceRepositoryURI))/pull/$(System.PullRequest.PullRequestNumber)
    echo "##vso[task.setvariable variable=CHANGE_URL]$value"
    temp=$(git merge-base origin/$(System.PullRequest.TargetBranch) $(System.PullRequest.SourceBranch))
    echo "##vso[task.setvariable variable=PREVIOUS_SHA]$temp"
  displayName: 'setting git variables' 

- script: |
    echo PREVIOUS_SHA
- script: |
    npm install
  displayName: 'install packages'

- script: | 
    CURRENT_SHA=$CURRENT_SHA CHANGE_URL=$CHANGE_URL PREVIOUS_SHA=$PREVIOUS_SHA npm run ui-test
  displayName: 'run ui-test'

# - script: | 
#       npm run happo-ci
#   displayName: 'run happo-ci'